"""A3 Permit Validator Agent using Gemini 2.5 Pro."""

from google.adk.agents import LlmAgent
from ..schemas.permit_schema import PermitGeneratorOutput
from ..tools.workorders import get_workorder_by_id
from ..tools.exit import exit_loop


def create_refiner_agent() -> LlmAgent:
    """
    Create A4 Permit Refiner Agent.
    
    Goal: Ensure each permit meets policy + standards; produce pass/fail & findings.
    LLM: Gemini 2.5 Flash, temperature=0
    Tools: rules.evaluate, rag.search, workorders.getById
    """
    
    agent = LlmAgent(
        model='gemini-2.5-flash',
        name='permit_refiner_agent',
        description="Refines the permits based on validations and recommendations, or calls exit_loop if critique indicates completion.",
        instruction="""You are a permit refiner agent. Your task is to:
1. Review the permits that were generated by the permit generator agent
2. Review the validation results and recommendations from the permit validator agent
3. Refine the permits based on the validation results and recommendations
4. If the validation indicates all permits pass (Pass status), call exit_loop to complete the refinement process
5. If there are errors or warnings, update the permits to address them

Update the permit generator output with the refined permits in the structured format. Note: You refine permits based on validation feedback.""",
        tools=[get_workorder_by_id, exit_loop],
        output_schema=PermitGeneratorOutput,
        output_key="permit_generator_output"
    )
    
    return agent

